# Generated by Django 5.1.3 on 2024-12-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_projects_descriptions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='project_img',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
