# Generated by Django 5.1.4 on 2024-12-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('your_name', models.CharField(max_length=100)),
                ('your_email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('messsage', models.TextField()),
            ],
        ),
    ]
